### ISSUE TITLE
Update object keys of `Measures` to match new spec

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-semantic-interfaces#10]
In the new world of dbt-core x MetricFlow the properties of measures are changing slightly.  Measure objects should have the following properties

| Property Name | Type | Description |
| --- | --- | --- |
| name | str | Name of the measure |
| agg | enum | Aggregation type |
| description | str | Description of the measure |
| expr | str | Expression of the measure |
| create_metric | Bool | Boolean flag that creates a metric from the measure if True |
| agg_params | Optional[AggregationParameters] | The aggregation parameters |
| non_additive_dimension | ? | Non-additive dimension parameters
| agg_time_dimension | str | The time dimension to aggregate the measure by |

The above properties are were pulled from https://github.com/dbt-labs/dbt-core/discussions/7456

**Comment by callum-mcdata** [comment]
Closing out this issue in favor of #35 because there aren't any changes to the spec as of right now. This will potentially change in the near future but we will have individual issues for each change
