### ISSUE TITLE
[Feature] Add `call_parameter_sets` to the `WhereFilter` Protocol

### ISSUE THREAD

**Issue by plypaul** [dbt-labs/dbt-semantic-interfaces#109]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

`call_parameter_sets` is currently a property on the Pydantic implementation of the `WhereFilter`. Since this property might be more broadly useful, it should be moved into the protocol definition.

### Are you interested in contributing this feature?

Yes

**Comment by QMalcolm** [comment]
To expand upon "more broadly used". What we're trying to solve with this is that the `where_sql_template` str is currently a highly structured string, but the string actually isn't guaranteed in the protocol in anyway. Although the protocol won't directly guarantee the the structure of the string, this allows us to write a validation that guarantees the the protocol. Moving the structure from not being controlled to being indirectly controlled.
