### ISSUE TITLE
[Feature] Bump pydantic to >=2.0.0

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-semantic-interfaces#134]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This package currently blocks users of dbt-core from upgrading Python projects to pydantic 2.0.0 which has the well-documented performance improvements.

**Comment by Jstein77** [comment]
Thanks for adding this issue Nial! Let me chat with the team about what it would take to upgrade pydantic.

**Comment by QMalcolm** [comment]
Thank you for the call out Nial 🙂 We've actually been waiting for the release of pydantic 2.0 for awhile, specifically because of the speed gains. Glad to see it's finally happened 🚀 

We should absolutely look at moving to pydantic 2 for this project. I was hoping it would be straight forward. However, it looks like it's gonna be a bit hands on. A number of things have been deprecated, `Optional` fields are no longer auto defaulted to `None`, `int`/`bool` values when parsing raw to string field are no longer gracefully handled, and etc. Full migration guide details can be [found here](https://docs.pydantic.dev/dev-v2/migration/).

**Comment by QMalcolm** [comment]
I've started a branch [qmalcolm--pydantic-2-support](https://github.com/dbt-labs/dbt-semantic-interfaces/tree/qmalcolm--pydantic-2-support)

**Comment by NiallRees** [comment]
Thanks @QMalcolm !

**Comment by elongl** [comment]
Hi @QMalcolm, can I help with anything?
There's also [this tool](https://github.com/pydantic/bump-pydantic) by the way.

**Comment by r-richmond** [comment]
Echoing the previous comment. @QMalcolm and/or other DBT folks is there anything that you need help with on this?
I saw we had this as a wishlist item for 0.3 but it was missed from [0.4](https://github.com/dbt-labs/dbt-semantic-interfaces/issues/191)

**Comment by gnilrets** [comment]
I want to put dbt in a dagster environment where we're using pydantic 2.0.  Can't do that until this is resolved.

**Comment by christeefy** [comment]
Curious to hear on the status of this work as well! It's currently blocking a project upgrade.

**Comment by christeefy** [comment]
Curious to hear on the status of this work as well, and if there's anything we can do to help!

**Comment by 18heim** [comment]
Looking forward to this dev !

**Comment by QMalcolm** [comment]
Hoooboy do I need to pay more attention to my github notifications 😅 We absolutely want to get dbt-semantic-intefaces migrated to Pydantic 2. However, we don't currently have a good idea of where that falls on our timeline. That said, we'd absolutely welcome community contributions to make it happen.

**Comment by r-richmond** [comment]
>That said, we'd absolutely welcome community contributions to make it happen.

Thanks for clarifying that @QMalcolm. I gave it a quick attempt and didn't get too far given my other time constraints. For anyone else who might want to try a community contribution I can say that getting the dev environment up and running with tests was pretty smooth & expect a bit more work than you think :).

**Comment by esciara** [comment]
Hi,

I wanted to help out, so I had a look.

The change does not seem straight forward at all.

@QMalcolm I tried to follow the same approach as you and started from [your branch on my own fork](https://github.com/esciara/dbt-semantic-interfaces/tree/qmalcolm--pydantic-2-support). I did the following:
- I rebased with `main` to be up-to-date.
- I updated the dependency to `pydantic~=2.5` to start with the latest version.
- I ran the `bump-pydantic` tool as suggested by @elongl .
- I organised the changes in commits, mimicking the way you did it to separate the changes in stages.
- I committed the code that still needs work (as suggested by `bump-pydantic`) in a "WIP" commit.

A lot of tests are not passing. I digged into some of them.

One of the main issue is that the deprecation of `__get_validators__` has a big impact, especially you used it to instantiate object during deserialisation by not using a `dict` or another instance of the same class,  but by using base types such as `str` for instance ([here is an example with `PydanticWhereFilter`](https://github.com/esciara/dbt-semantic-interfaces/blob/192881b290df06f4efd02079863c97ec191f1558/dbt_semantic_interfaces/implementations/filters/where_filter.py#L46-L47)). I could not find a way to emulate that with `__get_pydantic_core_schema__` (supposedly `__get_validators__`'s replacement).

Another issue with is that for some reason, validation fails on `XxxAsPydantic` classes as it thinks that the instances that are passed do not have the same type as expected, even though they seems to do... Probably has to do with them being created dynamically. Here is the result for running : 

```
test_dataclass_serialization.py::test_nested_dataclass FAILED            [100%]
test_dataclass_serialization.py:93 (test_nested_dataclass)

[..]

>           return PydanticModel(**field_values)
E           pydantic_core._pydantic_core.ValidationError: 1 validation error for NestedDataclassAsPydantic
E           field1
E             Input should be a valid dictionary or instance of SimpleDataclassAsPydantic [type=model_type, input_value=SimpleDataclassAsPydantic(field0=1), input_type=SimpleDataclassAsPydantic]
E               For further information visit https://errors.pydantic.dev/2.5/v/model_type

../dbt_semantic_interfaces/dataclass_serialization.py:223: ValidationError
```

Any guidance for a clue?

**Comment by esciara** [comment]
PR done. All tests passing.

**Comment by QMalcolm** [comment]
Bit of an update 😅 This is a copy and paste of my [comment on the PR](https://github.com/dbt-labs/dbt-semantic-interfaces/pull/217#issuecomment-1852904384)

> As we've been reviewing this we also realized we are likely going to have to support both Pydantic 1 and Pydantic 2 for quite some time. About [60 percent ](https://www.pepy.tech/projects/pydantic?versions=2.*&versions=1.*)of people using Pydantic are still on Pydantic 1. Pydantic 2 is very exciting. It's faster, and we plan to support it in 0.5 of DSI. Although we'd love to cut directly to just supporting Pydantic 2, that'll likely cause immediate pain for community.
>
> In regards to this PR, we still want to get it in. Currently we're investigating whether the changes in this PR will also work with any Pydantic 1 versions (hopefully at least 1.10.x). If that is not the case, we're then going to investigate if that would be possible with some slight tweaks to this PR. If that does not work, there are some crunchier ways for us to support both which we'd likely do in a separate PR if it came to that.

**Comment by WillAyd** [comment]
Looking forward to this change - the associated PR looks great. In case its helpful to have examples where this is problematic, Airflow 2.7.0 onwards uses pydantic 2.4.2 in its constraint files.

https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.11.txt
