### ISSUE TITLE
[Bug] PyPi version not matching project version

### ISSUE THREAD

**Issue by der-eismann** [dbt-labs/dbt-semantic-interfaces#137]
### Is this a new bug in dbt-semantic-interfaces?

- [X] I believe this is a new bug in dbt-semantic-interfaces
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

On [pypi.org](https://pypi.org/project/dbt-semantic-interfaces/#history), this project is said to have been released as version 0.2.0. However in the [pyproject.toml](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/pyproject.toml#L3) the version is still hardcoded as `0.1.0rc1` and git tags/releases don't exist at all. 

### Expected Behavior

pyproject.toml should have 0.2.0 as version and git tags/releases should be added.

### Steps To Reproduce

none

**Comment by QMalcolm** [comment]
Hi @der-eismann the code for 0.2.0 now lives in the branch [0.2.latest](https://github.com/dbt-labs/dbt-semantic-interfaces/tree/0.2.latest), and any patches for 0.2.x will happen on that branch. We have a [PR](https://github.com/dbt-labs/dbt-semantic-interfaces/pull/138) to bump main to 0.3.0a1. There is a tag for 0.2.0 (I just pushed the tag and then noticed this issue 🙃). I'll do a github release for it now. 

The release process for this repository is currently a fully manual process, something that we should resolve soon. Thank you for bearing with us.
