### ISSUE TITLE
Enable the `label` property to allow users to set a display name

### ISSUE THREAD

**Issue by mazinesy** [dbt-labs/dbt-semantic-interfaces#139]
**Describe the Feature**
I want to be able to retrieve a `display_name` from the domain objects.

Currently, `Metric` and `Dimension` domain objects do not have `display_name` as an attribute. It is available in the schema, but isn't defined at the domain level.

**Would you like to contribute?**
Certainly, but it is 2 LOC change.

**Anything Else?**
@nhandel I know there are some changes coming, maybe that is something that could be added ?

**Comment by tlento** [comment]
The documentation lists the `label` property as the place for this metadata for metrics, but unless I'm missing something it's not part of our jsonschema or protocol spec and therefore it's not clear how anybody would set it.

We should:

1. Add it to the jsonschema
2. Make it available for other object types (dimension, entity, and possibly measure)

**Comment by ataft** [comment]
Agreed, the `label` property should be available on [measures](https://docs.getdbt.com/docs/build/measures), [dimensions](https://docs.getdbt.com/docs/build/dimensions), and [entities](https://docs.getdbt.com/docs/build/entities). It appears to already by on measures, as per the docs, so should just be added to dimensions and entities.

**Comment by gneius** [comment]
👍 thx for logging this issue. The `label` property would be very useful for our integration.

**Comment by tlento** [comment]
We accidentally duplicated this, I'll close this out in favor of the newer issue, as we have some concerns over support for Entities - they're trickier than measures, dimensions, and metrics.
