### ISSUE TITLE
Add optional `label` attribute protocols

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-semantic-interfaces#143]
[dbt-core](https://github.com/dbt-labs/dbt-core) currently allows for specifying an optional `label` property  on [metric nodes](https://github.com/dbt-labs/dbt-core/blob/b39eeb328c9a245f21b54fb48f2761ad03d4d6ad/core/dbt/contracts/graph/nodes.py#L1463). However we don't currently specify this on the [metric protocol](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/ef8a893cc6e65f695db46356b8471a039246456b/dbt_semantic_interfaces/protocols/metric.py#L147). MetricFlow would like to begin using this property, and would like it to exist on more objects. 

We should add an optional `label` property to the following protocols:

- [Metric](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/ef8a893cc6e65f695db46356b8471a039246456b/dbt_semantic_interfaces/protocols/metric.py#L147)
- [SemanticModel](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/ef8a893cc6e65f695db46356b8471a039246456b/dbt_semantic_interfaces/protocols/semantic_model.py#L53)
- [Dimension](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/ef8a893cc6e65f695db46356b8471a039246456b/dbt_semantic_interfaces/protocols/dimension.py#L49)
- [Measure](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/ef8a893cc6e65f695db46356b8471a039246456b/dbt_semantic_interfaces/protocols/measure.py#L48)

**Comment by QMalcolm** [comment]
@nhandel should it be added to any other protocols?

**Comment by tlento** [comment]
Do we need SemanticModel? It doesn't matter much to me either way, I think Metric, Dimension, and Measure are the most important.

**Comment by tlento** [comment]
In the originally filed #139 users are requesting the label property be added to entities as well, so we need to consider how that might work.

**Comment by ataft** [comment]
I think it's worth the extra effort to have consistency and add `label` to entities. At the bare minimum, every object in the semantic layer should have:
1. id/code (dbt calls this name)
2. label/title
3. description

Semantic layers should also have attributes for synonyms, formatting, and more, but I understand dbt doesn't want to be too opinionated. Like others, I'll just use the `meta` attribute for these. I don't see `meta` in the [docs](https://docs.getdbt.com/docs/build/measures), but it's in the original [spec proposal](https://github.com/dbt-labs/dbt-core/discussions/7456).

**Comment by nhandel** [comment]
@QMalcolm this should also be added to the Entity object. We'll also need to add validation that each Entity with the same name either has the same label specified.

**Comment by tlento** [comment]
@ataft support for `meta` isn't available yet, but it is coming. You can follow along here: https://github.com/dbt-labs/dbt-core/issues/8511

**Comment by ataft** [comment]
@tlento I see from that issue that `meta` is being added for semantic models, but not dimensions and measures?

I was thinking/hoping that the new semantic layer could act as a "universal semantic layer" where I define everything (label, description, aggtype, meta for formatting and NLQ synonyms, etc.) that downstream tools could then just plug into. I was also hoping that the semantic layer YAML would replace the model and columns YAML, so I wouldn't need to define model columns and then separate measures and dimensions (seems redundant). Is the expectation that people will define a model and columns in one schema YAML file, then also define a semantic model with dimensions and metrics?

**Comment by emmyoop** [comment]
We've added labels in https://github.com/dbt-labs/dbt-core/pull/8646.  It is no longer a blocker on labels being supported.
