### ISSUE TITLE
[Feature] Figure out best way for Semantic Model -> Relationships to be established in dbt DAG

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-semantic-interfaces#22]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [ ] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Right now everything in dbt land is represented as a node in the DAG. These relationships are established with things like `ref('some_model')`.

Once we introduce the semantic constructs (metric & semantic model) we'll want those relationships to hold true. IE I should be able to see that model A feeds into semantic model B and Metric C.

🤔 

### Describe alternatives you've considered

Hiding?

### Who will this benefit?

Anyone who uses the semantic layer

### Are you interested in contributing this feature?

Yarp

**Comment by QMalcolm** [comment]
This is being handled in core by tickets focused on populating the `MetricNode.depends_on` property
