### ISSUE TITLE
[SL-1435] make the `label` attribute required

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-semantic-interfaces#228]
### Housekeeping

* [X] I am a maintainer of dbt-semantic-interfaces

### Short description

We want to make `label` attributes required such that people integrating with the semantic layer can go to one place, the `label`, of an object to use as a "Display Name"

### Acceptance criteria

All `label` attributes are required instead of optional.

### Impact to Other Teams

core

### Will backports be required?

Nope

### Context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [SL-1435](https://linear.app/dbt-labs/issue/SL-1435/make-the-label-attribute-required)</sub>

**Comment by Jstein77** [comment]
@QMalcolm QQ on this issue - label appears to already be required. What additional work do we need to do here? If I try to parse a project that has a metric configured without label I get the following error:

```
Parsing Error
  Invalid metrics config given in FilePath(searched_path='models', relative_path='staging/semantics/olist_closed_deals.yaml', modification_time=1702493977.6615357, project_root='/Users/jordanstein/Dev/jaffle-sl-template') @ metrics: {'name': 'conversion_rate_wow', 'description': 'Conversion rate wow', 'type': 'derived', 'type_params': {'expr': 'current_conversion_rate', 'metrics': [{'name': 'mql_to_seller_conversion_rate_base', 'alias': 'current_conversion_rate'}]}} - at path []: 'label' is a required property
```
