### ISSUE TITLE
[Bug] Please support pydantic-2.x

### ISSUE THREAD

**Issue by yurivict** [dbt-labs/dbt-semantic-interfaces#239]
### Is this a new bug in dbt-semantic-interfaces?

- [X] I believe this is a new bug in dbt-semantic-interfaces
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

[here](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/pyproject.toml#L23)

PYPI now has pydantic at 2.x and having two versions of Pydantic at the same time causes conflicts in resolving dependencies for some other packages, because pydantic-1.x and pydantic-2.x use the same namespace 'pydantic'.

### Expected Behavior

n/a

### Steps To Reproduce

n/a

### Relevant log output

```shell
n/a
```

### Environment

```markdown
- OS:
- Python:
- dbt:
- dbt-semantic-interfaces:
```

**Comment by QMalcolm** [comment]
Hi @yurivict! Thank you for submitting this issue 🙂 We already have an open issue for this work, https://github.com/dbt-labs/dbt-semantic-interfaces/issues/134. Additionally, we have an open PR to resolve the issue https://github.com/dbt-labs/dbt-semantic-interfaces/pull/238. I'm going to be closing this issue as a duplicate. Happy new year!

**Comment by yurivict** [comment]
@QMalcolm 

Why was this issue closed?
Dependencies still contain ``` "pydantic>=1.10,<3",```.
