### ISSUE TITLE
[Spec Update] Rename `measure_proxy` metric type to `simple`

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-semantic-interfaces#48]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Measure proxy isn't going to make as much sense in the new world of simple metrics & derived metrics. So let's rename it to simple!

**Comment by QMalcolm** [comment]
Resolved by https://github.com/dbt-labs/dbt-semantic-interfaces/pull/80
