### ISSUE TITLE
[Spec Update] Rename `is_primary` to `default_agg_time` 

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-semantic-interfaces#49]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As above so below. Let's do some renaming!

**Comment by QMalcolm** [comment]
Closed in favor of doing it all in #50
