### ISSUE TITLE
[Spec Update] Move `default_agg_time` to be in `default` struct within `SemanticModel`

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-semantic-interfaces#50]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This is a follow up after #49 . In reality this is more of a semantic model property than it is a dimension property.

**Comment by QMalcolm** [comment]
Resolved by https://github.com/dbt-labs/dbt-semantic-interfaces/pull/79
